#!/bin/bash
if [[ "$1" != "clean" ]]
then
  if [[ -z "${1// }" ]]
  then
    mkdir -p build
    for i in $(ls *.cpp)
    do
      g++ -c $i -I . -I include -w -lpthread -g -Wall -Wextra -Werror -pedantic -std=c++17
      g++ -O *.o -o build/${i%*.cpp} -I . -I include lib/libsfml-graphics.so.2.5.1 lib/libsfml-window.so.2.5.1 lib/libsfml-system.so.2.5.1 lib/libsfml-audio.so.2.5.1 -lpthread -g -Wall -Wextra -Werror -pedantic -std=c++17
      rm *.o
      echo "#!/bin/bash" > build/${i%*.cpp}.sh
      echo "cd \$0" >> build/${i%*.cpp}.sh
      echo "./"${i%*.cpp} >> build/${i%*.cpp}.sh
      chmod +x build/${i%*.cpp}.sh
      echo "#!/bin/bash" > build/${i%*.cpp}-debug.sh
      echo "cd \$0" >> build/${i%*.cpp}-debug.sh
      echo "gnome-terminal -- gdb ${i%*.cpp}" >> build/${i%*.cpp}-debug.sh
      chmod +x build/${i%*.cpp}-debug.sh
      echo "#!/bin/bash" > build/${i%*.cpp}-debug-mem-sh
      echo "cd \$0" >> build/${i%*.cpp}-debug-mem-sh
      echo "gnome-terminal -- /bin/sh -c 'valgrind --leak-check=yes -s ./${i%*.cpp}; exec bash'" >> build/${i%*.cpp}-debug-mem-sh
      chmod +x build/${i%*.cpp}-debug-mem-sh
    done
    cp fonts build -r
    cp textures build -r
  else
    mkdir -p build
    for i in $@
    do
      g++ -c $i -I . -I include -w -lpthread -g -Wall -Wextra -Werror -pedantic -std=c++17
      g++ -O *.o -o build/${i%*.cpp} -I . -I include lib/libsfml-graphics.so.2.5.1 lib/libsfml-window.so.2.5.1 lib/libsfml-system.so.2.5.1 lib/libsfml-audio.so.2.5.1 -lpthread -g -Wall -Wextra -Werror -pedantic -std=c++17
      rm *.o
      echo "#!/bin/bash" > build/${i%*.cpp}.sh
      echo "cd \$0" >> build/${i%*.cpp}.sh
      echo "./"${i%*.cpp} >> build/${i%*.cpp}.sh
      chmod +x build/${i%*.cpp}.sh
      echo "#!/bin/bash" > build/${i%*.cpp}-debug.sh
      echo "cd \$0" >> build/${i%*.cpp}-debug.sh
      echo "gnome-terminal -- gdb ${i%*.cpp}" >> build/${i%*.cpp}-debug.sh
      chmod +x build/${i%*.cpp}-debug.sh
      echo "#!/bin/bash" > build/${i%*.cpp}-debug-mem-sh
      echo "cd \$0" >> build/${i%*.cpp}-debug-mem-sh
      echo "gnome-terminal -- /bin/sh -c 'valgrind --leak-check=yes -s ./${i%*.cpp}; exec bash'" >> build/${i%*.cpp}-debug-mem-sh
      chmod +x build/${i%*.cpp}-debug-mem-sh
    done
    cp fonts build -r
    cp textures build -r
  fi
fi
if [[ "$1" == "clean" ]]
then
  rm build -r
fi
